name: Test

on:
  push:

jobs:
  test_make_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run documentation script
        run: |
          python scripts/make_docs.py

      - name: Check for Git differences
        run: |
          git diff --exit-code || exit 1
